### ISSUE TITLE
Allow modules to inform about failure

### ISSUE THREAD

**Issue by rasmuse** [ecodistrict/IDSSFramework#2]
At the moment we only allow two statuses in the `startModel` response: `"processing"` and `"success"`. It is conceivable that modules may fail due to invalid input or other problems. It should be possible to inform the dashboard about such a failure.

Is it good enough to just add a `"failed"` status, or should we do something more elaborate? Should there also be an optional value (perhaps named `info`) in the `startModel` response to send messages like `"Invalid input [blah blah]"` or `"Unhandled exception [blah blah]"`?

I'm open to suggestions.

**Comment by andreasrudena** [comment]
I think there should be additional statuses, I agree with this, and also the info optional value. This is supported in the dashboard = red, green and light blue colors on popping down notifications indicates error, success and info. But these could be used also as generic messages from modules with another type (`"notification"`?) and an optional `"info"` value. So what about extending every message specification to the dashboard with an optional notification thats sole purpose is to show to the user?: `notification: {type: 'error', info: 'This is a red error that the user will see'}`? 

Just throwing out some ideas..

**Comment by rasmuse** [comment]
How about this:

```
{
method: "startModule",
"type": "result",
"status": "failed",
"info": "Something went wrong!"
}
```
(where `info` property is optional and all others mandatory)

and for now let's skip notifications?

**Comment by rasmuse** [comment]
Decided and documented.
https://github.com/ecodistrict/IDSSFramework/wiki/Messaging-reference#startmodule-response
