### ISSUE TITLE
Decide on outputs formatting

### ISSUE THREAD

**Issue by rasmuse** [ecodistrict/IDSSFramework#3]
At the moment the rules for results sent in the `modelResult` message are not really defined.

Current state of affairs: `modelResult` message has an `outputs` property, which is a list of outputs chosen among some different types (at least `kpiValue` and `kpi-list` were demoed in Valencia).

Is this an acceptable structure? Do we have any reason to complicate this more?

In any case, we also need to decide on and document the allowed output types in the [wiki](https://github.com/ecodistrict/IDSSFramework/wiki).

**Comment by cornelissenja** [comment]
will be handled in the dashboard section
