### ISSUE TITLE
Connection lost after a while

### ISSUE THREAD

**Issue by mkeus** [ecodistrict/IDSSFramework#6]
When my client is connected to the IMB and listening for a long time, i noticed no calls came in anymore, for example when i call Getmodules. There is no disconnect event fired but the connection is lost. Is it possible to make a kind of keep alive/ heartbeat call to the bus, some sort of ping (hey i'am still here)

see also: http://www.codeproject.com/Articles/37490/Detection-of-Half-Open-Dropped-TCP-IP-Socket-Conne

**Comment by cornelissenja** [comment]
heartbeat added to Delphi and C#

**Comment by Joma564** [comment]
I have also noticed this when using the C# client.

**Comment by cornelissenja** [comment]
Implemented heartbeat in the C# IMB client, Martijn confirmed it's working ok..
